version: "3"

services:
  user.service:
    container_name: user.service
    environment:
      - RABBITMQ_URL=rabbitmq
      - MONGO_HOST=mongo-user
      - MONGO_PORT=27017
    build:
      context: ./services/user.service
    ports:
      - 3000:3000
      - 9229:9229
    links:
      - mongo-user
      - rabbitmq
    depends_on:
      - mongo-user
      - rabbitmq

  post.service:
    container_name: post.service
    environment:
      - RABBITMQ_URL=rabbitmq
      - MONGO_HOST=mongo-post
      - MONGO_PORT=27017
    build:
      context: ./services/post.service
    ports:
      - 3001:3001
      - 9230:9230
    links:
      - mongo-post
      - rabbitmq
    depends_on:
      - mongo-user
      - rabbitmq

  blob.service:
    container_name: blob.service
    environment:
      - RABBITMQ_URL=rabbitmq
      - MONGO_HOST=mongo-blob
      - MONGO_PORT=27017
    build:
      context: ./services/blob.service
    ports:
      - 3002:3002
      - 9231:9231
    links:
      - mongo-blob
      - rabbitmq
    depends_on:
      - mongo-user
      - rabbitmq

  notification.service:
    container_name: notification.service
    environment:
      - RABBITMQ_URL=rabbitmq
      - MONGO_HOST=mongo-notification
      - MONGO_PORT=27017
    build:
      context: ./services/notification.service
    ports:
      - 3003:3003
      - 9232:9232
    links:
      - mongo-notification
      - rabbitmq
    depends_on:
      - mongo-user
      - rabbitmq

  mongo-user:
    container_name: mongo-user
    image: mongo
    environment:
      #      - MONGO_INITDB_DATABASE=user-mongodb
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - /data/uniform/user-service/data:/data/db
    ports:
      - 27021:27017

  mongo-post:
    container_name: mongo-post
    image: mongo
    environment:
#      - MONGO_INITDB_DATABASE=post-mongodb
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - /data/uniform/post-service/data:/data/db
    ports:
      - 27018:27017

  mongo-blob:
    container_name: mongo-blob
    image: mongo
    environment:
#      - MONGO_INITDB_DATABASE=post-mongodb
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - /data/uniform/blob-service/data:/data/db
    ports:
      - 27019:27017

  mongo-notification:
    container_name: mongo-notification
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - /data/uniform/notification-service/data:/data/db
    ports:
      - 27020:27017

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
    - 15672:15672
    - 5672:5672

