version: "3"

services:
  user.service:
    container_name: user.service
    build:
      context: ./services/user.service
    ports:
      - 3000:3000
      - 9229:9229
    links:
      - mongo-user

  mongo-user:
    container_name: mongo-user
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=user.mongodb
#      - MONGO_INITDB_ROOT_USERNAME=test
#      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - /data/uniform/user-service/data:/data/db
    ports:
      - 27017:27017


  post.service:
    container_name: post.service
    build:
      context: ./services/post.service
    ports:
      - 3001:3001
      - 9230:9230
    links:
      - mongo-post

  mongo-post:
    container_name: mongo-post
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=post-mongodb
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - /data/uniform/post-service/data:/data/db
    ports:
      - 27018:27017


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
    - 15672:15672
    - 5672:5672

