env:
  node: true
  es6: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  new-cap: off
  require-jsdoc: off
  max-len: off

